language: php

sudo: required
dist: trusty

php:
  - '7.0'
  - '7.1'

services:
  - postgresql
  - mysql

git:
  depth: 1

env:
  global:
  - DB_ADAPTER=postgresql
  - DB_ADAPTER=mysql
  - DB_DATABASE=logger_test

before_script:
  - sh -c "if [ '$DB_ADAPTER' = 'postgresql' ]; then psql -c 'DROP DATABASE IF EXISTS logger_test;' -U postgres; fi"
  - sh -c "if [ '$DB_ADAPTER' = 'postgresql' ]; then psql -c 'CREATE DATABASE logger_test;' -U postgres; fi"
  - sh -c "if [ '$DB_ADAPTER' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS logger_test;'; fi"
addons:
  postgresql: "9.6"

